monolog:
    channels: ["video_stream"]
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
        video_stream:
            channels: [ "video_stream" ]
            path: "%kernel.logs_dir%/video_stream.log"
            level: info
            type: rotating_file
            max_files: 5
            filename_format: "{filename}_{date}"
            date_format: "Y"
